name: Deploy FastAPI App  # Name of the workflow

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to main

jobs:
  test:
    name: Run Tests  # Ensure code is valid before deploying
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone repo

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with pytest
        run: pytest  # Run tests; if any fail, deployment will not proceed

  deploy:
    name: Deploy Application  # Deployment job
    runs-on: ubuntu-latest  # Use an Ubuntu runner
    needs: test  # 👈 Ensures the "test" job must pass before deploying

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clone repo

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env: 
          BUILDX_GIT_INFO: false
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
            sudo docker stop fastapi-app || true
            sudo docker rm fastapi-app || true
            sudo docker run -d --restart unless-stopped --name fastapi-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
