name: Deploy FastAPI App  # Name of the workflow

on:
  push:
    branches:
      - main  # Triggers deployment when changes are pushed to main

jobs:
  deploy:
    name: Deploy Application  # Job name must be exactly "deploy"
    runs-on: ubuntu-latest  # Use an Ubuntu server for deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones the repository

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Store in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Store in GitHub Secrets

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}   # Your server IP or domain
          username: ${{ secrets.SERVER_USER }}  # Your SSH username
          key: ${{ secrets.SERVER_SSH_KEY }}  # Your private SSH key (GitHub Secret)
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
            docker stop fastapi-app || true
            docker rm fastapi-app || true
            docker run -d --name fastapi-app -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
