name: Run Tests  # Name of the workflow

on:
  pull_request:  # This triggers the workflow on PRs to main
    branches:
      - main

jobs:
  test:
    name: Run Pytest  # Job name
    runs-on: ubuntu-latest  # Use Ubuntu as the server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones your repo

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Change this if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: pytest
