name: Run Tests  # Name of the workflow

on:
  pull_request:  # Trigger only on pull requests to main
    branches:
      - main

jobs:
  test:  # The job MUST be named exactly "test"
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Clone the repository

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: |
          pip install pytest  # Install pytest (explicitly)
          pytest  # Run tests, failing if any test fails
