name: Run Tests  # Name of the workflow

on:
  pull_request:  # This triggers the workflow on PRs to main
    branches:
      - main

jobs:
  test:
    name: Run Pytest and Linting  # Job name
    runs-on: ubuntu-latest  # Use Ubuntu as the server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Clones your repo

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Change this if needed

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8  # Install linter

      - name: Run Linter (flake8)
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Tests with pytest
        run: |
          pytest --exitfirst --failed-first
